#spring.application.name=PostService
#
## MongoDB connection (note port 51026)
#spring.data.mongodb.uri=mongodb://root:secret@localhost:51026/MindConnectPostDB?authSource=admin
#spring.data.mongodb.database=MindConnectPostDB


spring.application.name=PostService

# Disable Docker Compose auto integration
spring.docker.compose.enabled=false

#mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authDB>
# MongoDB connection (running in Docker)
#spring.data.mongodb.uri=mongodb://root:secret@localhost:51026/MindConnectPostDB?authSource=admin
spring.data.mongodb.uri=mongodb://root:secret@mindconnect-mongo:27017/MindConnectPostDB?authSource=admin


spring.data.mongodb.database=MindConnectPostDB

spring.data.mongodb.auto-index-creation=false


#spring.kafka.bootstrap-servers=localhost:9092, localhost:9093, localhost:9094
#spring.kafka.bootstrap-servers=kafka1:9092, kafka2:9093, kafka3:9094
spring.kafka.bootstrap-servers=kafka1:19092,kafka2:19092,kafka3:19092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.properties.spring.json.add.type.headers=false

# Reliability
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.delivery-timeout=300000  # 5 mins

# Ordering / batching
#spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
#spring.kafka.producer.properties.linger.ms=5
#spring.kafka.producer.properties.batch.size=32768

# Compression
spring.kafka.producer.properties.compression.type=snappy
