#spring.application.name=PostService
#
## MongoDB connection (note port 51026)
#spring.data.mongodb.uri=mongodb://root:secret@localhost:51026/MindConnectPostDB?authSource=admin
#spring.data.mongodb.database=MindConnectPostDB


spring.application.name=PostService

# Disable Docker Compose auto integration
spring.docker.compose.enabled=false

# MongoDB connection (running in Docker)
spring.data.mongodb.uri=mongodb://root:secret@localhost:51026/MindConnectPostDB?authSource=admin
spring.data.mongodb.database=MindConnectPostDB

spring.data.mongodb.auto-index-creation=false